import { Comment } from '../comment';

export const commentData: { comment: Comment } = {
  comment: {
    all_awardings: [],
    approved_at_utc: null,
    associated_award: null,
    author: 'Jamie_EJ',
    author_flair_background_color: null,
    author_flair_css_class: null,
    author_flair_richtext: [],
    author_flair_template_id: null,
    author_flair_text: null,
    author_flair_text_color: null,
    author_flair_type: 'text',
    author_fullname: 't2_4u65znk2',
    author_patreon_flair: false,
    author_premium: false,
    awarders: [],
    banned_at_utc: null,
    body:
      "I just googled on this out of curiosity, and I found that all the troops and their dependants also get 15 day mandatory quarantine just like any others. [Here](https://8tharmy.korea.army.mil/site/newcomers/covid-19-arrival-info.asp)\n\nSo even if they do test positive, it's not like they're roaming around the streets with COVID19. The US troops testing postivie has been happening here and then since March or so, it seems. Maybe this time it's on a broader population? But it's gonna be taken care of, I believe, as always has been.",
    can_mod_post: false,
    collapsed: false,
    collapsed_because_crowd_control: null,
    collapsed_reason: null,
    comment_type: null,
    created_utc: 1602611996,
    distinguished: null,
    edited: false,
    gildings: {},
    id: 'g8ppwrc',
    is_submitter: false,
    link_id: 't3_jadfzo',
    locked: false,
    no_follow: true,
    parent_id: 't3_jadfzo',
    permalink:
      '/r/hanguk/comments/jadfzo/twentytwo_us_troops_test_positive_for_coronavirus/g8ppwrc/',
    retrieved_on: 1602613972,
    score: 1,
    send_replies: true,
    stickied: false,
    subreddit: 'hanguk',
    subreddit_id: 't5_2zq4v',
    top_awarded_type: null,
    total_awards_received: 0,
    treatment_tags: [],
  },
};
